import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Configure the Geist Sans font family
// This is the primary font used throughout the application
const geistSans = Geist({
  variable: "--font-geist-sans", // Creates a CSS custom property for the font
  subsets: ["latin"], // Only load Latin character subset for better performance
});

// Configure the Geist Mono font family  
// This is typically used for code snippets or monospace text
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Creates a CSS custom property for the monospace font
  subsets: ["latin"], // Only load Latin character subset for better performance
});

// Define metadata that will be applied to all pages in the application
// This includes the default title and description for SEO purposes
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component - This is the top-level layout that wraps all pages
// It's required in Next.js 13+ app directory and must contain html and body tags
// This layout is shared across all pages and persists during navigation
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // All page content will be passed as children
}>) {
  return (
    <html lang="en"> {/* Set the document language for accessibility and SEO */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Apply both font variables as CSS classes and enable font antialiasing for smoother text rendering
      >
        {children} {/* Render the actual page content here - this is where all your pages will be displayed */}
      </body>
    </html>
  );
}
